language: ruby
cache: bundler

rvm:
  - jruby
  - rbx
  - 2.0.0
  - 2.1.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - adriancasajus@gmail.com
    on_failure: change
    on_success: never